name: Wonseok Jeon's Blog
url: 'https://wsjeon.github.io/'
description: 'notes and thoughts from Wonseok'

exclude: [Gemfile, Gemfile.lock, README.md]
markdown: kramdown

author: 'Wonseok Jeon'

gems:
  # https://help.github.com/articles/atom-rss-feeds-for-github-pages/
  - jekyll-gist
  - jekyll-sitemap

sass:
    sass_dir: _sass
    style: :compressed
