name: Wonseok Jeon
url: 'https://wsjeon.github.io/'
description: ''

exclude: [Gemfile, Gemfile.lock, README.md]
markdown: kramdown

author: 'Wonseok Jeon'
disqus_shortname: wsjeon-github-io

gems:
  # https://help.github.com/articles/atom-rss-feeds-for-github-pages/
  - jekyll-gist
  - jekyll-sitemap

sass:
    sass_dir: _sass
    style: :compressed
